[package]
name = "ff-helper"
version = "0.0.1"
description = "ffmpeg helper by native binding"
authors = ["magicdawn"]
license = "MIT"
edition = "2021"
exclude = ["*.node"]

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
napi = { version = "2.12.2", features = ["napi4"] }
napi-derive = { version = "2.12.2" }
ffmpeg-next = "6.0.0"
ffmpeg-sys-next = "6.0.1"
once_cell = "1.17.1"
env_logger = "0.10.0"
log = "0.4.17"


[build-dependencies]
napi-build = "2.0.1"


[profile.release]
lto = true
