[package]
name = "ff-helper"
version = "0.0.1"
description = "ffmpeg helper by native binding"
authors = ["magicdawn"]
license = "MIT"
edition = "2021"
exclude = ["*.node"]

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
napi = { version = "2.14.1", features = ["napi4"] }
napi-derive = { version = "2.14.4" }
ffmpeg-next = "6.1.0"
ffmpeg-sys-next = "6.1.0"
once_cell = "1.19.0"
env_logger = "0.10.1"
log = "0.4.20"
image = "0.24.7"
rayon = "1.8.0"
mozjpeg = "0.10.5"


[build-dependencies]
napi-build = "2.1.0"


[profile.release]
lto = true
strip = "debuginfo"
