name: ci

on:
  - push
  - pull_request

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # no cache
      # - name: apt install
      #   run: sudo apt install -y clang pkg-config libavcodec-dev libavformat-dev libavutil-dev libavdevice-dev ffmpeg

      - name: apt install
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: clang pkg-config libavcodec-dev libavformat-dev libavutil-dev libavdevice-dev ffmpeg

      - uses: Swatinem/rust-cache@v2

      - uses: pnpm/action-setup@v2
        with: { version: 8 }

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - run: pnpm install

      # cache samples
      - uses: actions/cache@v3
        with:
          path: 'test/sample-videos/*.mp4'
          key: ${{ runner.os }}-${{ hashFiles('./test/setup.ts') }}

      # test
      - run: pnpm test-cover

      # test:report
      - uses: codecov/codecov-action@v3

      # typedoc
      - run: pnpm add typedoc -g
      - run: typedoc ./ts-src/index.ts

      - name: Deploy gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
