name: ci

on:
  - push
  - pull_request

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: apt install
        run: sudo apt install -y clang pkg-config libavcodec-dev libavformat-dev libavutil-dev libavdevice-dev

      - uses: pnpm/action-setup@v2
        with: { version: 7 }

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'

      - run: pnpm install

      # test
      # - run: pnpm test-cover

      # test:report
      # - uses: codecov/codecov-action@v3
